;;;
;;; custom-theme.el --- The color theme for Emacs.
;;; Version: 0.1
;;;

(deftheme custom "Custom color theme")

;;; Color Palette

(defvar custom-default-colors-alist
  '(("custom-border"                 . "#eee")
    ("custom-comment"                . "#9f9f9f")
    ("custom-constant"               . "#22B")
    ("custom-diff-added"             . "#e6ffed")
    ("custom-diff-added-highlight"   . "#acf2bd")
    ("custom-diff-changed"           . "#ffe1b9")
    ("custom-diff-changed-highlight" . "#ffc86f")
    ("custom-diff-removed"           . "#ffeef0")
    ("custom-diff-removed-highlight" . "#fdb8c0")
    ("custom-function"               . "#44f")
    ("custom-header-bg"              . "#d73a49")
    ("custom-header-fg"              . "#ffffff")
    ("custom-highlight"              . "#fffbdd")
    ("custom-header-bg"              . "#24292e")
    ("custom-header-fg"              . "#bcbdc0")
    ("custom-html-tag"               . "#22863a")
    ("custom-keyword"                . "#d73a49")
    ("custom-selection"              . "#3390ff")
    ("custom-string"                 . "#393")
    ("custom-text"                   . "#444")
    ("custom-white"                  . "#f9f9f9"))
  "List of GitHub colors.
Each element has the form (NAME . HEX).")

(defvar custom-override-colors-alist
  '()
  "Place to override default theme colors.

You can override a subset of the theme's default colors by
defining them in this alist before loading the theme.")

(defvar custom-colors-alist
  (append custom-default-colors-alist custom-override-colors-alist))

(defmacro custom-with-color-variables (&rest body)
  "`let' bind all colors defined in `custom-colors-alist' around BODY.
Also bind `class' to ((class color) (min-colors 89))."
  (declare (indent 0))
  `(let ((class '((class color) (min-colors 89)))
         ,@(mapcar (lambda (cons)
                     (list (intern (car cons)) (cdr cons)))
                   custom-colors-alist))
     ,@body))

;;; Theme Faces
(custom-with-color-variables
  (custom-theme-set-faces
   'custom
;;;; Built-in
;;;;; basic coloring
   '(button ((t (:underline t))))
   `(tool-bar ((t (:background ,custom-border :foreground "wheat" :box (:line-width 1 :style released-button)))))
   `(link ((t (:foreground ,custom-keyword :underline t :weight bold))))
   `(link-visited ((t (:foreground ,custom-text :underline t :weight normal))))
   `(default ((t (:foreground ,custom-text :background ,custom-white))))
   `(cursor ((t (:foreground ,custom-text :background ,custom-text))))
   `(escape-glyph ((t (:foreground ,custom-keyword :bold t))))
   `(fringe ((t (:foreground ,custom-text :background ,"#EEE"))))
   '(line-number ((t (:foreground ,custom-keyword :background ,custom-border))))
   `(header-line ((t (:foreground ,custom-keyword
                                  :background ,custom-selection
                                  :box (:line-width -1 :style released-button)))))
   `(highlight ((t (:background ,custom-highlight))))
   `(success ((t (:foreground ,custom-comment :weight bold))))
   `(warning ((t (:foreground ,custom-text :weight bold))))
   `(tooltip ((t (:foreground ,custom-text :background ,custom-white))))
;;;;; compilation
   `(compilation-column-face ((t (:foreground ,custom-keyword))))
   `(compilation-enter-directory-face ((t (:foreground ,custom-comment))))
   `(compilation-error-face ((t (:foreground ,custom-text :weight bold :underline t))))
   `(compilation-face ((t (:foreground ,custom-text))))
   `(compilation-info-face ((t (:foreground ,custom-text))))
   `(compilation-info ((t (:foreground ,custom-constant :underline t))))
   `(compilation-leave-directory-face ((t (:foreground ,custom-comment))))
   `(compilation-line-face ((t (:foreground ,custom-keyword))))
   `(compilation-line-number ((t (:foreground ,custom-keyword))))
   `(compilation-message-face ((t (:foreground ,custom-text))))
   `(compilation-warning-face ((t (:foreground ,custom-text :weight bold :underline t))))
   `(compilation-mode-line-exit ((t (:foreground ,custom-comment :weight bold))))
   `(compilation-mode-line-fail ((t (:foreground ,custom-string :weight bold))))
   `(compilation-mode-line-run ((t (:foreground ,custom-keyword :weight bold))))
;;;;; completions
   `(completions-annotations ((t (:foreground ,custom-text))))
;;;;; grep
   `(grep-context-face ((t (:foreground ,custom-text))))
   `(grep-error-face ((t (:foreground ,custom-text :weight bold :underline t))))
   `(grep-hit-face ((t (:foreground ,custom-text))))
   `(grep-match-face ((t (:foreground ,custom-text :weight bold))))
   `(match ((t (:background ,custom-selection :foreground ,custom-text :weight bold))))
;;;;; info
   `(Info-quoted ((t (:inherit font-lock-constant-face))))
;;;;; isearch
   `(isearch ((t (:foreground ,custom-white :weight bold :background ,custom-selection))))
   `(isearch-fail ((t (:foreground ,custom-border :background ,custom-white))))
   `(lazy-highlight ((t (:foreground ,custom-text :weight bold :background ,custom-highlight))))

   `(menu ((t (:foreground ,custom-text :background ,custom-border))))
   `(minibuffer-prompt ((t (:foreground ,custom-keyword))))
   `(mode-line
     ((,class (:foreground ,custom-header-fg
                           :background ,custom-header-bg))
      (t :inverse-video t)))
   `(mode-line-buffer-id ((t (:foreground ,custom-white :weight bold))))
   `(mode-line-inactive
     ((t (:foreground ,custom-comment
                      :background ,custom-white
                      :box (:line-width -1 :color ,custom-border)))))
   `(region ((,class (:background ,custom-selection))
             (t :inverse-video t)))
   `(secondary-selection ((t (:background ,custom-white))))
   `(trailing-whitespace ((t (:background ,custom-string))))
   `(vertical-border ((t (:foreground ,custom-border))))
;;;;; font lock
   `(font-lock-builtin-face ((t (:foreground ,custom-keyword))))
   `(font-lock-comment-face ((t (:foreground ,custom-comment))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,custom-comment))))
   `(font-lock-constant-face ((t (:foreground ,custom-constant))))
   `(font-lock-doc-face ((t (:foreground ,custom-string))))
   `(font-lock-function-name-face ((t (:foreground ,custom-function :weight bold))))
   `(font-lock-keyword-face ((t (:foreground ,custom-keyword))))
   `(font-lock-negation-char-face ((t (:foreground ,custom-keyword))))
   `(font-lock-preprocessor-face ((t (:foreground ,custom-keyword))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,custom-keyword))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,custom-comment))))
   `(font-lock-string-face ((t (:foreground ,custom-string))))
   `(font-lock-type-face ((t (:foreground ,custom-constant))))
   `(font-lock-variable-name-face ((t (:foreground ,custom-text))))
   `(font-lock-warning-face ((t (:foreground ,custom-text))))

   `(c-annotation-face ((t (:inherit font-lock-constant-face))))
;;;;; newsticker
   `(newsticker-date-face ((t (:foreground ,custom-text))))
   `(newsticker-default-face ((t (:foreground ,custom-text))))
   `(newsticker-enclosure-face ((t (:foreground ,custom-html-tag))))
   `(newsticker-extra-face ((t (:foreground ,custom-white :height 0.8))))
   `(newsticker-feed-face ((t (:foreground ,custom-text))))
   `(newsticker-immortal-item-face ((t (:foreground ,custom-comment))))
   `(newsticker-new-item-face ((t (:foreground ,custom-text))))
   `(newsticker-obsolete-item-face ((t (:foreground ,custom-string))))
   `(newsticker-old-item-face ((t (:foreground ,custom-white))))
   `(newsticker-statistics-face ((t (:foreground ,custom-text))))
   `(newsticker-treeview-face ((t (:foreground ,custom-text))))
   `(newsticker-treeview-immortal-face ((t (:foreground ,custom-comment))))
   `(newsticker-treeview-listwindow-face ((t (:foreground ,custom-text))))
   `(newsticker-treeview-new-face ((t (:foreground ,custom-text :weight bold))))
   `(newsticker-treeview-obsolete-face ((t (:foreground ,custom-string))))
   `(newsticker-treeview-old-face ((t (:foreground ,custom-white))))
   `(newsticker-treeview-selection-face ((t (:background ,custom-selection :foreground ,custom-keyword))))
;;;; Third-party
;;;;; ace-jump
   `(ace-jump-face-background
     ((t (:foreground ,custom-text :background ,custom-white :inverse-video nil))))
   `(ace-jump-face-foreground
     ((t (:foreground ,custom-comment :background ,custom-white :inverse-video nil))))
;;;;; ace-window
   `(aw-background-face
     ((t (:foreground ,custom-text :background ,custom-white :inverse-video nil))))
   `(aw-leading-char-face ((t (:foreground ,custom-white :background ,custom-keyword :weight bold))))
;;;;; android mode
   `(android-mode-debug-face ((t (:foreground ,custom-text))))
   `(android-mode-error-face ((t (:foreground ,custom-text :weight bold))))
   `(android-mode-info-face ((t (:foreground ,custom-text))))
   `(android-mode-verbose-face ((t (:foreground ,custom-comment))))
   `(android-mode-warning-face ((t (:foreground ,custom-keyword))))
;;;;; anzu
   `(anzu-mode-line ((t (:foreground ,custom-function :weight bold))))
   `(anzu-match-1 ((t (:foreground ,custom-white :background ,custom-comment))))
   `(anzu-match-2 ((t (:foreground ,custom-white :background ,custom-text))))
   `(anzu-match-3 ((t (:foreground ,custom-white :background ,custom-text))))
   `(anzu-replace-to ((t (:inherit anzu-replace-highlight :foreground ,custom-keyword))))
;;;;; auctex
   `(font-latex-bold-face ((t (:inherit bold))))
   `(font-latex-warning-face ((t (:foreground nil :inherit font-lock-warning-face))))
   `(font-latex-sectioning-5-face ((t (:foreground ,custom-string :weight bold ))))
   `(font-latex-sedate-face ((t (:foreground ,custom-keyword))))
   `(font-latex-italic-face ((t (:foreground ,custom-function :slant italic))))
   `(font-latex-string-face ((t (:inherit ,font-lock-string-face))))
   `(font-latex-math-face ((t (:foreground ,custom-text))))
;;;;; agda-mode
   `(agda2-highlight-keyword-face ((t (:foreground ,custom-keyword :weight bold))))
   `(agda2-highlight-string-face ((t (:foreground ,custom-string))))
   `(agda2-highlight-symbol-face ((t (:foreground ,custom-text))))
   `(agda2-highlight-primitive-type-face ((t (:foreground ,custom-constant))))
   `(agda2-highlight-inductive-constructor-face ((t (:foreground ,custom-text))))
   `(agda2-highlight-coinductive-constructor-face ((t (:foreground ,custom-text))))
   `(agda2-highlight-datatype-face ((t (:foreground ,custom-text))))
   `(agda2-highlight-function-face ((t (:foreground ,custom-text))))
   `(agda2-highlight-module-face ((t (:foreground ,custom-constant))))
   `(agda2-highlight-error-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(agda2-highlight-unsolved-meta-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(agda2-highlight-unsolved-constraint-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(agda2-highlight-termination-problem-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(agda2-highlight-incomplete-pattern-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(agda2-highlight-typechecks-face ((t (:background ,custom-text))))
;;;;; auto-complete
   `(ac-candidate-face ((t (:background ,custom-white :foreground ,custom-text))))
   `(ac-completion-face ((t (:background ,custom-selection :foreground ,custom-text))))
   `(ac-selection-face ((t (:background ,custom-selection :foreground ,custom-text))))
   `(popup-tip-face ((t (:background ,custom-text :foreground ,custom-white))))
   `(popup-scroll-bar-foreground-face ((t (:background ,custom-text))))
   `(popup-scroll-bar-background-face ((t (:background ,custom-comment))))
   `(popup-isearch-match ((t (:background ,custom-white :foreground ,custom-text))))
;;;;; avy
   `(avy-background-face
     ((t (:foreground ,custom-text :background ,custom-white :inverse-video nil))))
   `(avy-lead-face-0
     ((t (:foreground ,custom-html-tag :background ,custom-white :inverse-video nil :weight bold))))
   `(avy-lead-face-1
     ((t (:foreground ,custom-keyword :background ,custom-white :inverse-video nil :weight bold))))
   `(avy-lead-face-2
     ((t (:foreground ,custom-text :background ,custom-white :inverse-video nil :weight bold))))
   `(avy-lead-face
     ((t (:foreground ,custom-function :background ,custom-white :inverse-video nil :weight bold))))
;;;;; company-mode
   `(company-tooltip ((t (:foreground ,custom-text :background ,custom-white))))
   `(company-tooltip-annotation ((t (:foreground ,custom-text :background ,custom-white))))
   `(company-tooltip-annotation-selection ((t (:foreground ,custom-text :background ,custom-selection))))
   `(company-tooltip-selection ((t (:foreground ,custom-text :background ,custom-selection))))
   `(company-tooltip-mouse ((t (:background ,custom-selection))))
   `(company-tooltip-common ((t (:foreground ,custom-comment))))
   `(company-tooltip-common-selection ((t (:foreground ,custom-comment))))
   `(company-scrollbar-fg ((t (:background ,custom-text))))
   `(company-scrollbar-bg ((t (:background ,custom-white))))
   `(company-preview ((t (:background ,custom-comment))))
   `(company-preview-common ((t (:foreground ,custom-comment :background ,custom-selection))))
;;;;; bm
   `(bm-face ((t (:background ,custom-text :foreground ,custom-white))))
   `(bm-fringe-face ((t (:background ,custom-text :foreground ,custom-white))))
   `(bm-fringe-persistent-face ((t (:background ,custom-comment :foreground ,custom-white))))
   `(bm-persistent-face ((t (:background ,custom-comment :foreground ,custom-white))))
;;;;; cider
   `(cider-result-overlay-face ((t (:background unspecified))))
   `(cider-enlightened-face ((t (:box (:color ,custom-text :line-width -1)))))
   `(cider-enlightened-local-face ((t (:weight bold :foreground ,custom-text))))
   `(cider-deprecated-face ((t (:background ,custom-text))))
   `(cider-instrumented-face ((t (:box (:color ,custom-string :line-width -1)))))
   `(cider-traced-face ((t (:box (:color ,custom-function :line-width -1)))))
   `(cider-test-failure-face ((t (:background ,custom-text))))
   `(cider-test-error-face ((t (:background ,custom-text))))
   `(cider-test-success-face ((t (:background ,custom-comment))))
;;;;; circe
   `(circe-highlight-nick-face ((t (:foreground ,custom-function))))
   `(circe-my-message-face ((t (:foreground ,custom-text))))
   `(circe-fool-face ((t (:foreground ,custom-text))))
   `(circe-topic-diff-removed-face ((t (:foreground ,custom-string :weight bold))))
   `(circe-originator-face ((t (:foreground ,custom-text))))
   `(circe-server-face ((t (:foreground ,custom-comment))))
   `(circe-topic-diff-new-face ((t (:foreground ,custom-text :weight bold))))
   `(circe-prompt-face ((t (:foreground ,custom-text :background ,custom-white :weight bold))))
;;;;; context-coloring
   `(context-coloring-level-0-face ((t :foreground ,custom-text)))
   `(context-coloring-level-1-face ((t :foreground ,custom-function)))
   `(context-coloring-level-2-face ((t :foreground ,custom-constant)))
   `(context-coloring-level-3-face ((t :foreground ,custom-keyword)))
   `(context-coloring-level-4-face ((t :foreground ,custom-text)))
   `(context-coloring-level-5-face ((t :foreground ,custom-text)))
   `(context-coloring-level-6-face ((t :foreground ,custom-keyword)))
   `(context-coloring-level-7-face ((t :foreground ,custom-comment)))
   `(context-coloring-level-8-face ((t :foreground ,custom-text)))
   `(context-coloring-level-9-face ((t :foreground ,custom-text)))
;;;;; coq
   `(coq-solve-tactics-face ((t (:foreground nil :inherit font-lock-constant-face))))
;;;;; ctable
   `(ctbl:face-cell-select ((t (:background ,custom-text :foreground ,custom-white))))
   `(ctbl:face-continue-bar ((t (:background ,custom-highlight :foreground ,custom-white))))
   `(ctbl:face-row-select ((t (:background ,custom-function :foreground ,custom-white))))
;;;;; diff
   `(diff-added          ((t (:background ,custom-diff-added :foreground ,custom-text))))
   `(diff-changed        ((t (:background ,custom-diff-changed :foreground ,custom-text))))
   `(diff-removed        ((t (:background ,custom-diff-removed :foreground ,custom-text))))
   `(diff-refine-added   ((t (:background ,custom-diff-added-highlight :foreground ,custom-text))))
   `(diff-refine-change  ((t (:background ,custom-diff-changed-highlight :foreground ,custom-text))))
   `(diff-refine-removed ((t (:background ,custom-diff-removed-highlight :foreground ,custom-text))))
   `(diff-header ((,class (:background ,custom-white))
                  (t (:background ,custom-text :foreground ,custom-white))))
   `(diff-file-header
     ((,class (:background ,custom-white :foreground ,custom-text :bold t))
      (t (:background ,custom-text :foreground ,custom-white :bold t))))
;;;;; diff-hl
   `(diff-hl-change ((,class (:foreground ,custom-text :background ,custom-diff-added))))
   `(diff-hl-delete ((,class (:foreground ,custom-text :background ,custom-diff-removed-highlight))))
   `(diff-hl-insert ((,class (:foreground ,custom-text :background ,custom-diff-added-highlight))))
;;;;; dim-autoload
   `(dim-autoload-cookie-line ((t :foreground ,custom-white)))
;;;;; dired+
   `(diredp-display-msg ((t (:foreground ,custom-text))))
   `(diredp-compressed-file-suffix ((t (:foreground ,custom-text))))
   `(diredp-date-time ((t (:foreground ,custom-text))))
   `(diredp-deletion ((t (:foreground ,custom-keyword))))
   `(diredp-deletion-file-name ((t (:foreground ,custom-string))))
   `(diredp-dir-heading ((t (:foreground ,custom-text :background ,custom-selection))))
   `(diredp-dir-priv ((t (:foreground ,custom-function))))
   `(diredp-exec-priv ((t (:foreground ,custom-string))))
   `(diredp-executable-tag ((t (:foreground ,custom-text))))
   `(diredp-file-name ((t (:foreground ,custom-text))))
   `(diredp-file-suffix ((t (:foreground ,custom-comment))))
   `(diredp-flag-mark ((t (:foreground ,custom-keyword))))
   `(diredp-flag-mark-line ((t (:foreground ,custom-text))))
   `(diredp-ignored-file-name ((t (:foreground ,custom-string))))
   `(diredp-link-priv ((t (:foreground ,custom-keyword))))
   `(diredp-mode-line-flagged ((t (:foreground ,custom-keyword))))
   `(diredp-mode-line-marked ((t (:foreground ,custom-text))))
   `(diredp-no-priv ((t (:foreground ,custom-text))))
   `(diredp-number ((t (:foreground ,custom-text))))
   `(diredp-other-priv ((t (:foreground ,custom-text))))
   `(diredp-rare-priv ((t (:foreground ,custom-text))))
   `(diredp-read-priv ((t (:foreground ,custom-comment))))
   `(diredp-symlink ((t (:foreground ,custom-keyword))))
   `(diredp-write-priv ((t (:foreground ,custom-text))))
;;;;; dired-async
   `(dired-async-failures ((t (:foreground ,custom-string :weight bold))))
   `(dired-async-message ((t (:foreground ,custom-keyword :weight bold))))
   `(dired-async-mode-message ((t (:foreground ,custom-keyword))))
;;;;; ediff
   `(ediff-current-diff-A ((t (:foreground ,custom-text :background ,custom-diff-removed))))
   `(ediff-current-diff-Ancestor ((t (:foreground ,custom-text :background ,custom-text))))
   `(ediff-current-diff-B ((t (:foreground ,custom-text :background ,custom-diff-added))))
   `(ediff-current-diff-C ((t (:foreground ,custom-text :background ,custom-text))))
   `(ediff-even-diff-A ((t (:background ,custom-white))))
   `(ediff-even-diff-Ancestor ((t (:background ,custom-white))))
   `(ediff-even-diff-B ((t (:background ,custom-white))))
   `(ediff-even-diff-C ((t (:background ,custom-white))))
   `(ediff-fine-diff-A ((t (:foreground ,custom-text :background ,custom-diff-removed-highlight :weight bold))))
   `(ediff-fine-diff-Ancestor ((t (:foreground ,custom-text :background ,custom-text weight bold))))
   `(ediff-fine-diff-B ((t (:foreground ,custom-text :background ,custom-diff-added-highlight :weight bold))))
   `(ediff-fine-diff-C ((t (:foreground ,custom-text :background ,custom-text :weight bold ))))
   `(ediff-odd-diff-A ((t (:background ,custom-white))))
   `(ediff-odd-diff-Ancestor ((t (:background ,custom-white))))
   `(ediff-odd-diff-B ((t (:background ,custom-white))))
   `(ediff-odd-diff-C ((t (:background ,custom-white))))
;;;;; egg
   `(egg-text-base ((t (:foreground ,custom-text))))
   `(egg-help-header-1 ((t (:foreground ,custom-keyword))))
   `(egg-help-header-2 ((t (:foreground ,custom-html-tag))))
   `(egg-branch ((t (:foreground ,custom-keyword))))
   `(egg-branch-mono ((t (:foreground ,custom-keyword))))
   `(egg-term ((t (:foreground ,custom-keyword))))
   `(egg-diff-add ((t (:foreground ,custom-constant))))
   `(egg-diff-del ((t (:foreground ,custom-text))))
   `(egg-diff-file-header ((t (:foreground ,custom-text))))
   `(egg-section-title ((t (:foreground ,custom-keyword))))
   `(egg-stash-mono ((t (:foreground ,custom-constant))))
;;;;; elfeed
   `(elfeed-log-error-level-face ((t (:foreground ,custom-string))))
   `(elfeed-log-info-level-face ((t (:foreground ,custom-text))))
   `(elfeed-log-warn-level-face ((t (:foreground ,custom-keyword))))
   `(elfeed-search-date-face ((t (:foreground ,custom-text :underline t
                                              :weight bold))))
   `(elfeed-search-tag-face ((t (:foreground ,custom-comment))))
   `(elfeed-search-feed-face ((t (:foreground ,custom-function))))
;;;;; emacs-w3m
   `(w3m-anchor ((t (:foreground ,custom-keyword :underline t
                                 :weight bold))))
   `(w3m-arrived-anchor ((t (:foreground ,custom-text
                                         :underline t :weight normal))))
   `(w3m-form ((t (:foreground ,custom-text :underline t))))
   `(w3m-header-line-location-title ((t (:foreground ,custom-keyword
                                                     :underline t :weight bold))))
   '(w3m-history-current-url ((t (:inherit match))))
   `(w3m-lnum ((t (:foreground ,custom-comment :background ,custom-white))))
   `(w3m-lnum-match ((t (:background ,custom-selection
                                     :foreground ,custom-text
                                     :weight bold))))
   `(w3m-lnum-minibuffer-prompt ((t (:foreground ,custom-keyword))))
;;;;; erc
   `(erc-action-face ((t (:inherit erc-default-face))))
   `(erc-bold-face ((t (:weight bold))))
   `(erc-current-nick-face ((t (:foreground ,custom-text :weight bold))))
   `(erc-dangerous-host-face ((t (:inherit font-lock-warning-face))))
   `(erc-default-face ((t (:foreground ,custom-text))))
   `(erc-direct-msg-face ((t (:inherit erc-default-face))))
   `(erc-error-face ((t (:inherit font-lock-warning-face))))
   `(erc-fool-face ((t (:inherit erc-default-face))))
   `(erc-highlight-face ((t (:inherit hover-highlight))))
   `(erc-input-face ((t (:foreground ,custom-keyword))))
   `(erc-keyword-face ((t (:foreground ,custom-text :weight bold))))
   `(erc-nick-default-face ((t (:foreground ,custom-keyword :weight bold))))
   `(erc-my-nick-face ((t (:foreground ,custom-string :weight bold))))
   `(erc-nick-msg-face ((t (:inherit erc-default-face))))
   `(erc-notice-face ((t (:foreground ,custom-comment))))
   `(erc-pal-face ((t (:foreground ,custom-text :weight bold))))
   `(erc-prompt-face ((t (:foreground ,custom-text :background ,custom-white :weight bold))))
   `(erc-timestamp-face ((t (:foreground ,custom-constant))))
   `(erc-underline-face ((t (:underline t))))
;;;;; ert
   `(ert-test-result-expected ((t (:foreground ,custom-constant :background ,custom-white))))
   `(ert-test-result-unexpected ((t (:foreground ,custom-string :background ,custom-white))))
;;;;; eshell
   `(eshell-prompt ((t (:foreground ,custom-keyword :weight bold))))
   `(eshell-ls-archive ((t (:foreground ,custom-text :weight bold))))
   `(eshell-ls-backup ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-clutter ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-directory ((t (:foreground ,custom-keyword :weight bold))))
   `(eshell-ls-executable ((t (:foreground ,custom-text :weight bold))))
   `(eshell-ls-unreadable ((t (:foreground ,custom-text))))
   `(eshell-ls-missing ((t (:inherit font-lock-warning-face))))
   `(eshell-ls-product ((t (:inherit font-lock-doc-face))))
   `(eshell-ls-special ((t (:foreground ,custom-keyword :weight bold))))
   `(eshell-ls-symlink ((t (:foreground ,custom-function :weight bold))))
;;;;; flx
   `(flx-highlight-face ((t (:foreground ,custom-comment :weight bold))))
;;;;; flycheck
   `(flycheck-error
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-text) :inherit unspecified))
      (t (:foreground ,custom-text :weight bold :underline t))))
   `(flycheck-warning
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-keyword) :inherit unspecified))
      (t (:foreground ,custom-keyword :weight bold :underline t))))
   `(flycheck-info
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-function) :inherit unspecified))
      (t (:foreground ,custom-function :weight bold :underline t))))
   `(flycheck-fringe-error ((t (:foreground ,custom-text :weight bold))))
   `(flycheck-fringe-warning ((t (:foreground ,custom-keyword :weight bold))))
   `(flycheck-fringe-info ((t (:foreground ,custom-function :weight bold))))
;;;;; flymake
   `(flymake-errline
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-string)
                   :inherit unspecified :foreground unspecified :background unspecified))
      (t (:foreground ,custom-text :weight bold :underline t))))
   `(flymake-warnline
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-text)
                   :inherit unspecified :foreground unspecified :background unspecified))
      (t (:foreground ,custom-text :weight bold :underline t))))
   `(flymake-infoline
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-comment)
                   :inherit unspecified :foreground unspecified :background unspecified))
      (t (:foreground ,custom-comment :weight bold :underline t))))
;;;;; flyspell
   `(flyspell-duplicate
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-text) :inherit unspecified))
      (t (:foreground ,custom-text :weight bold :underline t))))
   `(flyspell-incorrect
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-string) :inherit unspecified))
      (t (:foreground ,custom-text :weight bold :underline t))))
;;;;; full-ack
   `(ack-separator ((t (:foreground ,custom-text))))
   `(ack-file ((t (:foreground ,custom-text))))
   `(ack-line ((t (:foreground ,custom-keyword))))
   `(ack-match ((t (:foreground ,custom-text :background ,custom-selection :weight bold))))
;;;;; git-commit
   `(git-commit-comment-action  ((,class (:foreground ,custom-text :weight bold))))
   `(git-commit-comment-branch  ((,class (:foreground ,custom-keyword  :weight bold))))
   `(git-commit-comment-heading ((,class (:foreground ,custom-keyword  :weight bold))))
;;;;; git-gutter
   `(git-gutter:added ((t (:foreground ,custom-constant :weight bold))))
   `(git-gutter:deleted ((t (:foreground ,custom-keyword :weight bold))))
   `(git-gutter:modified ((t (:foreground ,custom-string :weight bold))))
   `(git-gutter:unchanged ((t (:foreground ,custom-text :weight bold :inverse-video t))))
;;;;; git-gutter-fr
   `(git-gutter-fr:added ((t (:foreground ,custom-comment  :weight bold))))
   `(git-gutter-fr:deleted ((t (:foreground ,custom-string :weight bold))))
   `(git-gutter-fr:modified ((t (:foreground ,custom-text :weight bold))))
;;;;; git-rebase
   `(git-rebase-hash ((t (:foreground, custom-text))))
;;;;; gnus
   `(gnus-group-mail-1 ((t (:bold t :inherit gnus-group-mail-1-empty))))
   `(gnus-group-mail-1-empty ((t (:inherit gnus-group-news-1-empty))))
   `(gnus-group-mail-2 ((t (:bold t :inherit gnus-group-mail-2-empty))))
   `(gnus-group-mail-2-empty ((t (:inherit gnus-group-news-2-empty))))
   `(gnus-group-mail-3 ((t (:bold t :inherit gnus-group-mail-3-empty))))
   `(gnus-group-mail-3-empty ((t (:inherit gnus-group-news-3-empty))))
   `(gnus-group-mail-4 ((t (:bold t :inherit gnus-group-mail-4-empty))))
   `(gnus-group-mail-4-empty ((t (:inherit gnus-group-news-4-empty))))
   `(gnus-group-mail-5 ((t (:bold t :inherit gnus-group-mail-5-empty))))
   `(gnus-group-mail-5-empty ((t (:inherit gnus-group-news-5-empty))))
   `(gnus-group-mail-6 ((t (:bold t :inherit gnus-group-mail-6-empty))))
   `(gnus-group-mail-6-empty ((t (:inherit gnus-group-news-6-empty))))
   `(gnus-group-mail-low ((t (:bold t :inherit gnus-group-mail-low-empty))))
   `(gnus-group-mail-low-empty ((t (:inherit gnus-group-news-low-empty))))
   `(gnus-group-news-1 ((t (:bold t :inherit gnus-group-news-1-empty))))
   `(gnus-group-news-2 ((t (:bold t :inherit gnus-group-news-2-empty))))
   `(gnus-group-news-3 ((t (:bold t :inherit gnus-group-news-3-empty))))
   `(gnus-group-news-4 ((t (:bold t :inherit gnus-group-news-4-empty))))
   `(gnus-group-news-5 ((t (:bold t :inherit gnus-group-news-5-empty))))
   `(gnus-group-news-6 ((t (:bold t :inherit gnus-group-news-6-empty))))
   `(gnus-group-news-low ((t (:bold t :inherit gnus-group-news-low-empty))))
   `(gnus-header-content ((t (:inherit message-header-other))))
   `(gnus-header-from ((t (:inherit message-header-to))))
   `(gnus-header-name ((t (:inherit message-header-name))))
   `(gnus-header-newsgroups ((t (:inherit message-header-other))))
   `(gnus-header-subject ((t (:inherit message-header-subject))))
   `(gnus-server-opened ((t (:foreground ,custom-comment :weight bold))))
   `(gnus-server-denied ((t (:foreground ,custom-text :weight bold))))
   `(gnus-server-closed ((t (:foreground ,custom-text :slant italic))))
   `(gnus-server-offline ((t (:foreground ,custom-keyword :weight bold))))
   `(gnus-server-agent ((t (:foreground ,custom-text :weight bold))))
   `(gnus-summary-cancelled ((t (:foreground ,custom-text))))
   `(gnus-summary-high-ancient ((t (:foreground ,custom-text))))
   `(gnus-summary-high-read ((t (:foreground ,custom-comment :weight bold))))
   `(gnus-summary-high-ticked ((t (:foreground ,custom-text :weight bold))))
   `(gnus-summary-high-unread ((t (:foreground ,custom-text :weight bold))))
   `(gnus-summary-low-ancient ((t (:foreground ,custom-text))))
   `(gnus-summary-low-read ((t (:foreground ,custom-comment))))
   `(gnus-summary-low-ticked ((t (:foreground ,custom-text :weight bold))))
   `(gnus-summary-low-unread ((t (:foreground ,custom-text))))
   `(gnus-summary-normal-ancient ((t (:foreground ,custom-text))))
   `(gnus-summary-normal-read ((t (:foreground ,custom-comment))))
   `(gnus-summary-normal-ticked ((t (:foreground ,custom-text :weight bold))))
   `(gnus-summary-normal-unread ((t (:foreground ,custom-text))))
   `(gnus-summary-selected ((t (:foreground ,custom-keyword :weight bold))))
   `(gnus-cite-1 ((t (:foreground ,custom-text))))
   `(gnus-cite-10 ((t (:foreground ,custom-text))))
   `(gnus-cite-11 ((t (:foreground ,custom-keyword))))
   `(gnus-cite-2 ((t (:foreground ,custom-constant))))
   `(gnus-cite-3 ((t (:foreground ,custom-text))))
   `(gnus-cite-4 ((t (:foreground ,custom-comment))))
   `(gnus-cite-5 ((t (:foreground ,custom-text))))
   `(gnus-cite-6 ((t (:foreground ,custom-comment))))
   `(gnus-cite-7 ((t (:foreground ,custom-string))))
   `(gnus-cite-8 ((t (:foreground ,custom-text))))
   `(gnus-cite-9 ((t (:foreground ,custom-text))))
   `(gnus-group-news-1-empty ((t (:foreground ,custom-keyword))))
   `(gnus-group-news-2-empty ((t (:foreground ,custom-html-tag))))
   `(gnus-group-news-3-empty ((t (:foreground ,custom-text))))
   `(gnus-group-news-4-empty ((t (:foreground ,custom-text))))
   `(gnus-group-news-5-empty ((t (:foreground ,custom-text))))
   `(gnus-group-news-6-empty ((t (:foreground ,custom-white))))
   `(gnus-group-news-low-empty ((t (:foreground ,custom-white))))
   `(gnus-signature ((t (:foreground ,custom-keyword))))
   `(gnus-x ((t (:background ,custom-text :foreground ,custom-white))))
;;;;; guide-key
   `(guide-key/highlight-command-face ((t (:foreground ,custom-text))))
   `(guide-key/key-face ((t (:foreground ,custom-comment))))
   `(guide-key/prefix-command-face ((t (:foreground ,custom-text))))
;;;;; helm
   `(helm-header
     ((t (:foreground ,custom-comment
                      :background ,custom-white
                      :underline nil
                      :box nil))))
   `(helm-source-header
     ((t (:foreground ,custom-keyword
                      :background ,custom-selection
                      :underline nil
                      :weight bold
                      :box (:line-width -1 :style released-button)))))
   `(helm-selection ((t (:background ,custom-highlight :underline nil))))
   `(helm-selection-line ((t (:background ,custom-white))))
   `(helm-visible-mark ((t (:foreground ,custom-white :background ,custom-text))))
   `(helm-candidate-number ((t (:foreground ,custom-constant :background ,custom-selection))))
   `(helm-separator ((t (:foreground ,custom-string :background ,custom-white))))
   `(helm-time-zone-current ((t (:foreground ,custom-comment :background ,custom-white))))
   `(helm-time-zone-home ((t (:foreground ,custom-string :background ,custom-white))))
   `(helm-bookmark-addressbook ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-bookmark-directory ((t (:foreground nil :background nil :inherit helm-ff-directory))))
   `(helm-bookmark-file ((t (:foreground nil :background nil :inherit helm-ff-file))))
   `(helm-bookmark-gnus ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-bookmark-info ((t (:foreground ,custom-comment :background ,custom-white))))
   `(helm-bookmark-man ((t (:foreground ,custom-keyword :background ,custom-white))))
   `(helm-bookmark-w3m ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-buffer-not-saved ((t (:foreground ,custom-string :background ,custom-white))))
   `(helm-buffer-process ((t (:foreground ,custom-function :background ,custom-white))))
   `(helm-buffer-saved-out ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-buffer-size ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-ff-directory ((t (:foreground ,custom-function :background ,custom-white :weight bold))))
   `(helm-ff-file ((t (:foreground ,custom-text :background ,custom-white :weight normal))))
   `(helm-ff-executable ((t (:foreground ,custom-comment :background ,custom-white :weight normal))))
   `(helm-ff-invalid-symlink ((t (:foreground ,custom-string :background ,custom-white :weight bold))))
   `(helm-ff-symlink ((t (:foreground ,custom-keyword :background ,custom-white :weight bold))))
   `(helm-ff-prefix ((t (:foreground ,custom-white :background ,custom-keyword :weight normal))))
   `(helm-grep-cmd-line ((t (:foreground ,custom-function :background ,custom-white))))
   `(helm-grep-file ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-grep-finish ((t (:foreground ,custom-comment :background ,custom-white))))
   `(helm-grep-lineno ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-grep-match ((t (:foreground nil :background nil :inherit helm-match))))
   `(helm-grep-running ((t (:foreground ,custom-string :background ,custom-white))))
   `(helm-match ((t (:foreground ,custom-text :background ,custom-selection :weight bold))))
   `(helm-moccur-buffer ((t (:foreground ,custom-function :background ,custom-white))))
   `(helm-mu-contacts-address-face ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-mu-contacts-name-face ((t (:foreground ,custom-text :background ,custom-white))))
;;;;; helm-swoop
   `(helm-swoop-target-line-face ((t (:foreground ,custom-text :background ,custom-white))))
   `(helm-swoop-target-word-face ((t (:foreground ,custom-keyword :background ,custom-white :weight bold))))
;;;;; highlight-numbers
   `(highlight-numbers-number ((t (:foreground ,custom-constant))))
;;;;; hl-line-mode
   `(hl-line-face ((,class (:background ,custom-highlight))
                   (t :weight bold)))
   `(hl-line ((,class (:background ,custom-highlight)) ; old emacsen
              (t :weight bold)))
;;;;; hl-sexp
   `(hl-sexp-face ((,class (:background ,custom-white))
                   (t :weight bold)))
;;;;; hlinum
   `(linum-highlight-face ((t (:foreground ,custom-comment :background ,custom-highlight))))
;;;;; hydra
   `(hydra-face-red ((t (:foreground ,custom-text :background ,custom-white))))
   `(hydra-face-amaranth ((t (:foreground ,custom-text :background ,custom-white))))
   `(hydra-face-blue ((t (:foreground ,custom-text :background ,custom-white))))
   `(hydra-face-pink ((t (:foreground ,custom-text :background ,custom-white))))
   `(hydra-face-teal ((t (:foreground ,custom-function :background ,custom-white))))
;;;;; ivy
   `(ivy-confirm-face ((t (:foreground ,custom-comment :background ,custom-white))))
   `(ivy-match-required-face ((t (:foreground ,custom-string :background ,custom-white))))
   `(ivy-remote ((t (:foreground ,custom-text :background ,custom-white))))
   `(ivy-subdir ((t (:foreground ,custom-keyword :background ,custom-white))))
   `(ivy-current-match ((t (:foreground ,custom-keyword :weight bold :underline t))))
   `(ivy-minibuffer-match-face-1 ((t (:background ,custom-white))))
   `(ivy-minibuffer-match-face-2 ((t (:background ,custom-comment))))
   `(ivy-minibuffer-match-face-3 ((t (:background ,custom-comment))))
   `(ivy-minibuffer-match-face-4 ((t (:background ,custom-text))))
;;;;; ido-mode
   `(ido-first-match ((t (:foreground ,custom-keyword :weight bold))))
   `(ido-only-match ((t (:foreground ,custom-text :weight bold))))
   `(ido-subdir ((t (:foreground ,custom-keyword))))
   `(ido-indicator ((t (:foreground ,custom-keyword :background ,custom-text))))
;;;;; iedit-mode
   `(iedit-occurrence ((t (:background ,custom-white :weight bold))))
;;;;; jabber-mode
   `(jabber-roster-user-away ((t (:foreground ,custom-comment))))
   `(jabber-roster-user-online ((t (:foreground ,custom-constant))))
   `(jabber-roster-user-dnd ((t (:foreground ,custom-text))))
   `(jabber-roster-user-xa ((t (:foreground ,custom-text))))
   `(jabber-roster-user-chatty ((t (:foreground ,custom-text))))
   `(jabber-roster-user-error ((t (:foreground ,custom-text))))
   `(jabber-rare-time-face ((t (:foreground ,custom-text))))
   `(jabber-chat-prompt-local ((t (:foreground ,custom-constant))))
   `(jabber-chat-prompt-foreign ((t (:foreground ,custom-text))))
   `(jabber-chat-prompt-system ((t (:foreground ,custom-html-tag))))
   `(jabber-activity-face((t (:foreground ,custom-text))))
   `(jabber-activity-personal-face ((t (:foreground ,custom-keyword))))
   `(jabber-title-small ((t (:height 1.1 :weight bold))))
   `(jabber-title-medium ((t (:height 1.2 :weight bold))))
   `(jabber-title-large ((t (:height 1.3 :weight bold))))
;;;;; js2-mode
   `(js2-warning ((t (:underline ,custom-text))))
   `(js2-error ((t (:foreground ,custom-string :weight bold))))
   `(js2-jsdoc-tag ((t (:foreground ,custom-comment))))
   `(js2-jsdoc-type ((t (:foreground ,custom-comment))))
   `(js2-jsdoc-value ((t (:foreground ,custom-html-tag))))
   `(js2-function-param ((t (:foreground, custom-text))))
   `(js2-external-variable ((t (:foreground ,custom-text))))
;;;;; additional js2 mode attributes for better syntax highlighting
   `(js2-instance-member ((t (:foreground ,custom-comment))))
   `(js2-jsdoc-html-tag-delimiter ((t (:foreground ,custom-text))))
   `(js2-jsdoc-html-tag-name ((t (:foreground ,custom-text))))
   `(js2-object-property ((t (:foreground ,custom-keyword))))
   `(js2-magic-paren ((t (:foreground ,custom-text))))
   `(js2-private-function-call ((t (:foreground ,custom-function))))
   `(js2-function-call ((t (:foreground ,custom-function))))
   `(js2-private-member ((t (:foreground ,custom-constant))))
   `(js2-keywords ((t (:foreground ,custom-text))))
;;;;; ledger-mode
   `(ledger-font-payee-uncleared-face ((t (:foreground ,custom-text :weight bold))))
   `(ledger-font-payee-cleared-face ((t (:foreground ,custom-text :weight normal))))
   `(ledger-font-xact-highlight-face ((t (:background ,custom-white))))
   `(ledger-font-pending-face ((t (:foreground ,custom-text weight: normal))))
   `(ledger-font-other-face ((t (:foreground ,custom-text))))
   `(ledger-font-posting-account-face ((t (:foreground ,custom-constant))))
   `(ledger-font-posting-account-cleared-face ((t (:foreground ,custom-text))))
   `(ledger-font-posting-account-pending-face ((t (:foreground ,custom-text))))
   `(ledger-font-posting-amount-face ((t (:foreground ,custom-text))))
   `(ledger-occur-narrowed-face ((t (:foreground ,custom-text :invisible t))))
   `(ledger-occur-xact-face ((t (:background ,custom-white))))
   `(ledger-font-comment-face ((t (:foreground ,custom-comment))))
   `(ledger-font-reconciler-uncleared-face ((t (:foreground ,custom-text :weight bold))))
   `(ledger-font-reconciler-cleared-face ((t (:foreground ,custom-text :weight normal))))
   `(ledger-font-reconciler-pending-face ((t (:foreground ,custom-text :weight normal))))
   `(ledger-font-report-clickable-face ((t (:foreground ,custom-text :weight normal))))
;;;;; linum-mode
   `(linum ((t (:foreground ,custom-comment :background ,custom-white))))
;;;;; lispy
   `(lispy-command-name-face ((t (:background ,custom-highlight :inherit font-lock-function-name-face))))
   `(lispy-cursor-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(lispy-face-hint ((t (:inherit highlight :foreground ,custom-keyword))))
;;;;; ruler-mode
   `(ruler-mode-column-number ((t (:inherit 'ruler-mode-default :foreground ,custom-text))))
   `(ruler-mode-fill-column ((t (:inherit 'ruler-mode-default :foreground ,custom-keyword))))
   `(ruler-mode-goal-column ((t (:inherit 'ruler-mode-fill-column))))
   `(ruler-mode-comment-column ((t (:inherit 'ruler-mode-fill-column))))
   `(ruler-mode-tab-stop ((t (:inherit 'ruler-mode-fill-column))))
   `(ruler-mode-current-column ((t (:foreground ,custom-keyword :box t))))
   `(ruler-mode-default ((t (:foreground ,custom-comment :background ,custom-white))))

;;;;; lui
   `(lui-time-stamp-face ((t (:foreground ,custom-constant))))
   `(lui-hilight-face ((t (:foreground ,custom-comment :background ,custom-white))))
   `(lui-button-face ((t (:inherit hover-highlight))))
;;;;; macrostep
   `(macrostep-gensym-1
     ((t (:foreground ,custom-comment :background ,custom-selection))))
   `(macrostep-gensym-2
     ((t (:foreground ,custom-text :background ,custom-selection))))
   `(macrostep-gensym-3
     ((t (:foreground ,custom-keyword :background ,custom-selection))))
   `(macrostep-gensym-4
     ((t (:foreground ,custom-text :background ,custom-selection))))
   `(macrostep-gensym-5
     ((t (:foreground ,custom-keyword :background ,custom-selection))))
   `(macrostep-expansion-highlight-face
     ((t (:inherit highlight))))
   `(macrostep-macro-face
     ((t (:underline t))))
;;;;; magit
;;;;;; headings and diffs
   `(magit-section-highlight           ((t (:background ,custom-white))))
   `(magit-section-heading             ((t (:foreground ,custom-keyword :weight bold))))
   `(magit-section-heading-selection   ((t (:foreground ,custom-text :weight bold))))
   `(magit-diff-file-heading           ((t (:weight bold))))
   `(magit-diff-file-heading-highlight ((t (:background ,custom-white  :weight bold))))
   `(magit-diff-file-heading-selection ((t (:background ,custom-white
                                                        :foreground ,custom-text :weight bold))))
   `(magit-diff-hunk-heading           ((t (:background ,custom-white))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,custom-white))))
   `(magit-diff-hunk-heading-selection ((t (:background ,custom-white
                                                        :foreground ,custom-text))))
   `(magit-diff-lines-heading          ((t (:background ,custom-text
                                                        :foreground ,custom-white))))
   `(magit-diff-context-highlight      ((t (:background ,custom-white
                                                        :foreground "grey70"))))
   `(magit-diffstat-added   ((t (:foreground ,custom-constant))))
   `(magit-diffstat-removed ((t (:foreground ,custom-string))))
;;;;;; popup
   `(magit-popup-heading             ((t (:foreground ,custom-keyword  :weight bold))))
   `(magit-popup-key                 ((t (:foreground ,custom-comment :weight bold))))
   `(magit-popup-argument            ((t (:foreground ,custom-comment   :weight bold))))
   `(magit-popup-disabled-argument   ((t (:foreground ,custom-text    :weight normal))))
   `(magit-popup-option-value        ((t (:foreground ,custom-text  :weight bold))))
;;;;;; process
   `(magit-process-ok    ((t (:foreground ,custom-comment  :weight bold))))
   `(magit-process-ng    ((t (:foreground ,custom-string    :weight bold))))
;;;;;; log
   `(magit-log-author    ((t (:foreground ,custom-text))))
   `(magit-log-date      ((t (:foreground ,custom-text))))
   `(magit-log-graph     ((t (:foreground ,custom-text))))
;;;;;; sequence
   `(magit-sequence-pick ((t (:foreground ,custom-text))))
   `(magit-sequence-stop ((t (:foreground ,custom-comment))))
   `(magit-sequence-part ((t (:foreground ,custom-keyword))))
   `(magit-sequence-head ((t (:foreground ,custom-text))))
   `(magit-sequence-drop ((t (:foreground ,custom-string))))
   `(magit-sequence-done ((t (:foreground ,custom-text))))
   `(magit-sequence-onto ((t (:foreground ,custom-text))))
;;;;;; bisect
   `(magit-bisect-good ((t (:foreground ,custom-comment))))
   `(magit-bisect-skip ((t (:foreground ,custom-keyword))))
   `(magit-bisect-bad  ((t (:foreground ,custom-string))))
;;;;;; blame
   `(magit-blame-heading ((t (:background ,custom-selection :foreground ,custom-text))))
   `(magit-blame-hash    ((t (:background ,custom-selection :foreground ,custom-text))))
   `(magit-blame-name    ((t (:background ,custom-selection :foreground ,custom-text))))
   `(magit-blame-date    ((t (:background ,custom-selection :foreground ,custom-text))))
   `(magit-blame-summary ((t (:background ,custom-selection :foreground ,custom-text
                                          :weight bold))))
;;;;;; references etc
   `(magit-dimmed         ((t (:foreground ,custom-text))))
   `(magit-hash           ((t (:foreground ,custom-text))))
   `(magit-tag            ((t (:foreground ,custom-text :weight bold))))
   `(magit-branch-remote  ((t (:foreground ,custom-comment  :weight bold))))
   `(magit-branch-local   ((t (:foreground ,custom-text   :weight bold))))
   `(magit-branch-current ((t (:foreground ,custom-text   :weight bold :box t))))
   `(magit-head           ((t (:foreground ,custom-text   :weight bold))))
   `(magit-refname        ((t (:background ,custom-white :foreground ,custom-text :weight bold))))
   `(magit-refname-stash  ((t (:background ,custom-white :foreground ,custom-text :weight bold))))
   `(magit-refname-wip    ((t (:background ,custom-white :foreground ,custom-text :weight bold))))
   `(magit-signature-good      ((t (:foreground ,custom-comment))))
   `(magit-signature-bad       ((t (:foreground ,custom-string))))
   `(magit-signature-untrusted ((t (:foreground ,custom-keyword))))
   `(magit-cherry-unmatched    ((t (:foreground ,custom-function))))
   `(magit-cherry-equivalent   ((t (:foreground ,custom-text))))
   `(magit-reflog-commit       ((t (:foreground ,custom-comment))))
   `(magit-reflog-amend        ((t (:foreground ,custom-text))))
   `(magit-reflog-merge        ((t (:foreground ,custom-comment))))
   `(magit-reflog-checkout     ((t (:foreground ,custom-text))))
   `(magit-reflog-reset        ((t (:foreground ,custom-string))))
   `(magit-reflog-rebase       ((t (:foreground ,custom-text))))
   `(magit-reflog-cherry-pick  ((t (:foreground ,custom-comment))))
   `(magit-reflog-remote       ((t (:foreground ,custom-function))))
   `(magit-reflog-other        ((t (:foreground ,custom-function))))
;;;;; message-mode
   `(message-cited-text ((t (:inherit font-lock-comment-face))))
   `(message-header-name ((t (:foreground ,custom-text))))
   `(message-header-other ((t (:foreground ,custom-comment))))
   `(message-header-to ((t (:foreground ,custom-keyword :weight bold))))
   `(message-header-cc ((t (:foreground ,custom-keyword :weight bold))))
   `(message-header-newsgroups ((t (:foreground ,custom-keyword :weight bold))))
   `(message-header-subject ((t (:foreground ,custom-text :weight bold))))
   `(message-header-xheader ((t (:foreground ,custom-comment))))
   `(message-mml ((t (:foreground ,custom-keyword :weight bold))))
   `(message-separator ((t (:inherit font-lock-comment-face))))
;;;;; mew
   `(mew-face-header-subject ((t (:foreground ,custom-text))))
   `(mew-face-header-from ((t (:foreground ,custom-keyword))))
   `(mew-face-header-date ((t (:foreground ,custom-comment))))
   `(mew-face-header-to ((t (:foreground ,custom-string))))
   `(mew-face-header-key ((t (:foreground ,custom-comment))))
   `(mew-face-header-private ((t (:foreground ,custom-comment))))
   `(mew-face-header-important ((t (:foreground ,custom-text))))
   `(mew-face-header-marginal ((t (:foreground ,custom-text :weight bold))))
   `(mew-face-header-warning ((t (:foreground ,custom-string))))
   `(mew-face-header-xmew ((t (:foreground ,custom-comment))))
   `(mew-face-header-xmew-bad ((t (:foreground ,custom-string))))
   `(mew-face-body-url ((t (:foreground ,custom-text))))
   `(mew-face-body-comment ((t (:foreground ,custom-text :slant italic))))
   `(mew-face-body-cite1 ((t (:foreground ,custom-comment))))
   `(mew-face-body-cite2 ((t (:foreground ,custom-text))))
   `(mew-face-body-cite3 ((t (:foreground ,custom-text))))
   `(mew-face-body-cite4 ((t (:foreground ,custom-keyword))))
   `(mew-face-body-cite5 ((t (:foreground ,custom-string))))
   `(mew-face-mark-review ((t (:foreground ,custom-text))))
   `(mew-face-mark-escape ((t (:foreground ,custom-comment))))
   `(mew-face-mark-delete ((t (:foreground ,custom-string))))
   `(mew-face-mark-unlink ((t (:foreground ,custom-keyword))))
   `(mew-face-mark-refile ((t (:foreground ,custom-comment))))
   `(mew-face-mark-unread ((t (:foreground ,custom-text))))
   `(mew-face-eof-message ((t (:foreground ,custom-comment))))
   `(mew-face-eof-part ((t (:foreground ,custom-keyword))))
;;;;; mic-paren
   `(paren-face-match ((t (:foreground ,custom-function :background ,custom-white :weight bold))))
   `(paren-face-mismatch ((t (:foreground ,custom-white :background ,custom-text :weight bold))))
   `(paren-face-no-match ((t (:foreground ,custom-white :background ,custom-string :weight bold))))
;;;;; mingus
   `(mingus-directory-face ((t (:foreground ,custom-text))))
   `(mingus-pausing-face ((t (:foreground ,custom-text))))
   `(mingus-playing-face ((t (:foreground ,custom-function))))
   `(mingus-playlist-face ((t (:foreground ,custom-function ))))
   `(mingus-song-file-face ((t (:foreground ,custom-keyword))))
   `(mingus-stopped-face ((t (:foreground ,custom-string))))
;;;;; nav
   `(nav-face-heading ((t (:foreground ,custom-keyword))))
   `(nav-face-button-num ((t (:foreground ,custom-function))))
   `(nav-face-dir ((t (:foreground ,custom-comment))))
   `(nav-face-hdir ((t (:foreground ,custom-string))))
   `(nav-face-file ((t (:foreground ,custom-text))))
   `(nav-face-hfile ((t (:foreground ,custom-text))))
;;;;; mu4e
   `(mu4e-cited-1-face ((t (:foreground ,custom-text    :slant italic))))
   `(mu4e-cited-2-face ((t (:foreground ,custom-comment :slant italic))))
   `(mu4e-cited-3-face ((t (:foreground ,custom-text  :slant italic))))
   `(mu4e-cited-4-face ((t (:foreground ,custom-comment   :slant italic))))
   `(mu4e-cited-5-face ((t (:foreground ,custom-text  :slant italic))))
   `(mu4e-cited-6-face ((t (:foreground ,custom-comment :slant italic))))
   `(mu4e-cited-7-face ((t (:foreground ,custom-text    :slant italic))))
   `(mu4e-replied-face ((t (:foreground ,custom-text))))
   `(mu4e-trashed-face ((t (:foreground ,custom-text :strike-through t))))
;;;;; mumamo
   `(mumamo-background-chunk-major ((t (:background nil))))
   `(mumamo-background-chunk-submode1 ((t (:background ,custom-selection))))
   `(mumamo-background-chunk-submode2 ((t (:background ,custom-white))))
   `(mumamo-background-chunk-submode3 ((t (:background ,custom-white))))
   `(mumamo-background-chunk-submode4 ((t (:background ,custom-white))))
;;;;; neotree
   `(neo-banner-face ((t (:foreground ,custom-keyword :weight bold))))
   `(neo-header-face ((t (:foreground ,custom-text))))
   `(neo-root-dir-face ((t (:foreground ,custom-keyword :weight bold))))
   `(neo-dir-link-face ((t (:foreground ,custom-text))))
   `(neo-file-link-face ((t (:foreground ,custom-text))))
   `(neo-expand-btn-face ((t (:foreground ,custom-text))))
   `(neo-vc-default-face ((t (:foreground ,custom-text))))
   `(neo-vc-user-face ((t (:foreground ,custom-string :slant italic))))
   `(neo-vc-up-to-date-face ((t (:foreground ,custom-text))))
   `(neo-vc-edited-face ((t (:foreground ,custom-text))))
   `(neo-vc-needs-merge-face ((t (:foreground ,custom-text))))
   `(neo-vc-unlocked-changes-face ((t (:foreground ,custom-string :background ,custom-text))))
   `(neo-vc-added-face ((t (:foreground ,custom-text))))
   `(neo-vc-conflict-face ((t (:foreground ,custom-text))))
   `(neo-vc-missing-face ((t (:foreground ,custom-text))))
   `(neo-vc-ignored-face ((t (:foreground ,custom-text))))
;;;;; org-mode
   `(org-agenda-clocking
     ((t (:bold t :background ,custom-highlight))) t)
   `(org-agenda-date-today
     ((t (:foreground ,custom-text :slant italic :weight bold))) t)
   `(org-agenda-structure
     ((t (:inherit font-lock-comment-face))))
   `(org-archived ((t (:foreground ,custom-text :weight bold))))
   `(org-checkbox ((t (:background ,custom-white :foreground ,custom-text
                                   :box (:line-width 1 :style released-button)))))
   `(org-date ((t (:foreground ,custom-text :underline t))))
   `(org-deadline-announce ((t (:foreground ,custom-text))))
   `(org-done ((t (:bold t :weight bold :foreground ,custom-html-tag))))
   `(org-formula ((t (:foreground ,custom-text))))
   `(org-headline-done ((t (:foreground ,custom-html-tag))))
   `(org-hide ((t (:foreground ,custom-selection))))
   `(org-level-1 ((t (:foreground ,custom-text))))
   `(org-level-2 ((t (:foreground ,custom-constant))))
   `(org-level-3 ((t (:foreground ,custom-constant))))
   `(org-level-4 ((t (:foreground ,custom-text))))
   `(org-level-5 ((t (:foreground ,custom-function))))
   `(org-level-6 ((t (:foreground ,custom-comment))))
   `(org-level-7 ((t (:foreground ,custom-text))))
   `(org-level-8 ((t (:foreground ,custom-text))))
   `(org-link ((t (:foreground ,custom-text :underline t))))
   `(org-scheduled ((t (:foreground ,custom-constant))))
   `(org-scheduled-previously ((t (:foreground ,custom-string))))
   `(org-scheduled-today ((t (:foreground ,custom-keyword))))
   `(org-sexp-date ((t (:foreground ,custom-keyword :underline t))))
   `(org-special-keyword ((t (:inherit font-lock-comment-face))))
   `(org-table ((t (:foreground ,custom-comment))))
   `(org-tag ((t (:bold t :weight bold))))
   `(org-time-grid ((t (:foreground ,custom-text))))
   `(org-todo ((t (:bold t :foreground ,custom-string :weight bold))))
   `(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
   `(org-warning ((t (:bold t :foreground ,custom-string :weight bold :underline nil))))
   `(org-column ((t (:background ,custom-selection))))
   `(org-column-title ((t (:background ,custom-selection :underline t :weight bold))))
   `(org-mode-line-clock ((t (:foreground ,custom-text :background ,custom-selection))))
   `(org-mode-line-clock-overrun ((t (:foreground ,custom-white :background ,custom-text))))
   `(org-ellipsis ((t (:foreground ,custom-text :underline t))))
   `(org-footnote ((t (:foreground ,custom-function :underline t))))
   `(org-document-title ((t (:foreground ,custom-text))))
   `(org-document-info ((t (:foreground ,custom-text))))
   `(org-habit-ready-face ((t :background ,custom-comment)))
   `(org-habit-alert-face ((t :background ,custom-text :foreground ,custom-white)))
   `(org-habit-clear-face ((t :background ,custom-text)))
   `(org-habit-overdue-face ((t :background ,custom-text)))
   `(org-habit-clear-future-face ((t :background ,custom-text)))
   `(org-habit-ready-future-face ((t :background ,custom-comment)))
   `(org-habit-alert-future-face ((t :background ,custom-text :foreground ,custom-white)))
   `(org-habit-overdue-future-face ((t :background ,custom-text)))
;;;;; outline
   `(outline-1 ((t (:foreground ,custom-text))))
   `(outline-2 ((t (:foreground ,custom-constant))))
   `(outline-3 ((t (:foreground ,custom-constant))))
   `(outline-4 ((t (:foreground ,custom-text))))
   `(outline-5 ((t (:foreground ,custom-function))))
   `(outline-6 ((t (:foreground ,custom-comment))))
   `(outline-7 ((t (:foreground ,custom-text))))
   `(outline-8 ((t (:foreground ,custom-text))))
;;;;; p4
   `(p4-depot-added-face ((t :inherit diff-added)))
   `(p4-depot-branch-op-face ((t :inherit diff-changed)))
   `(p4-depot-deleted-face ((t :inherit diff-removed)))
   `(p4-depot-unmapped-face ((t :inherit diff-changed)))
   `(p4-diff-change-face ((t :inherit diff-changed)))
   `(p4-diff-del-face ((t :inherit diff-removed)))
   `(p4-diff-file-face ((t :inherit diff-file-header)))
   `(p4-diff-head-face ((t :inherit diff-header)))
   `(p4-diff-ins-face ((t :inherit diff-added)))
;;;;; perspective
   `(persp-selected-face ((t (:foreground ,custom-text :inherit mode-line))))
;;;;; powerline
   `(powerline-active1 ((t (:background ,custom-string :inherit mode-line))))
   `(powerline-active2 ((t (:background ,custom-keyword :inherit mode-line))))
   `(powerline-inactive1 ((t (:background ,custom-white :inherit mode-line-inactive))))
   `(powerline-inactive2 ((t (:background ,custom-white :inherit mode-line-inactive))))
;;;;; proofgeneral
   `(proof-active-area-face ((t (:underline t))))
   `(proof-boring-face ((t (:foreground ,custom-text :background ,custom-white))))
   `(proof-command-mouse-highlight-face ((t (:inherit proof-mouse-highlight-face))))
   `(proof-debug-message-face ((t (:inherit proof-boring-face))))
   `(proof-declaration-name-face ((t (:inherit font-lock-keyword-face :foreground nil))))
   `(proof-eager-annotation-face ((t (:foreground ,custom-white :background ,custom-text))))
   `(proof-error-face ((t (:foreground ,custom-text :background ,custom-text))))
   `(proof-highlight-dependency-face ((t (:foreground ,custom-white :background ,custom-comment))))
   `(proof-highlight-dependent-face ((t (:foreground ,custom-white :background ,custom-comment))))
   `(proof-locked-face ((t (:background ,custom-comment))))
   `(proof-mouse-highlight-face ((t (:foreground ,custom-white :background ,custom-comment))))
   `(proof-queue-face ((t (:background ,custom-comment))))
   `(proof-region-mouse-highlight-face ((t (:inherit proof-mouse-highlight-face))))
   `(proof-script-highlight-error-face ((t (:background ,custom-comment))))
   `(proof-tacticals-name-face ((t (:inherit font-lock-constant-face :foreground nil :background ,custom-white))))
   `(proof-tactics-name-face ((t (:inherit font-lock-constant-face :foreground nil :background ,custom-white))))
   `(proof-warning-face ((t (:foreground ,custom-white :background ,custom-comment))))
;;;;; racket-mode
   `(racket-keyword-argument-face ((t (:inherit font-lock-constant-face))))
   `(racket-selfeval-face ((t (:inherit font-lock-type-face))))
;;;;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,custom-constant))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,custom-function))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,custom-keyword))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-10-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-11-face ((t (:foreground ,custom-comment))))
   `(rainbow-delimiters-depth-12-face ((t (:foreground ,custom-comment))))
;;;;; rcirc
   `(rcirc-my-nick ((t (:foreground ,custom-comment))))
   `(rcirc-other-nick ((t (:foreground ,custom-comment))))
   `(rcirc-bright-nick ((t (:foreground ,custom-keyword))))
   `(rcirc-dim-nick ((t (:foreground ,custom-comment))))
   `(rcirc-server ((t (:foreground ,custom-comment))))
   `(rcirc-server-prefix ((t (:foreground ,custom-comment))))
   `(rcirc-timestamp ((t (:foreground ,custom-comment))))
   `(rcirc-nick-in-message ((t (:foreground ,custom-keyword))))
   `(rcirc-nick-in-message-full-line ((t (:bold t))))
   `(rcirc-prompt ((t (:foreground ,custom-keyword :bold t))))
   `(rcirc-track-nick ((t (:inverse-video t))))
   `(rcirc-track-keyword ((t (:bold t))))
   `(rcirc-url ((t (:bold t))))
   `(rcirc-keyword ((t (:foreground ,custom-keyword :bold t))))
;;;;; rpm-mode
   `(rpm-spec-dir-face ((t (:foreground ,custom-comment))))
   `(rpm-spec-doc-face ((t (:foreground ,custom-comment))))
   `(rpm-spec-ghost-face ((t (:foreground ,custom-string))))
   `(rpm-spec-macro-face ((t (:foreground ,custom-keyword))))
   `(rpm-spec-obsolete-tag-face ((t (:foreground ,custom-string))))
   `(rpm-spec-package-face ((t (:foreground ,custom-string))))
   `(rpm-spec-section-face ((t (:foreground ,custom-keyword))))
   `(rpm-spec-tag-face ((t (:foreground ,custom-comment))))
   `(rpm-spec-var-face ((t (:foreground ,custom-string))))
;;;;; rst-mode
   `(rst-level-1-face ((t (:foreground ,custom-comment))))
   `(rst-level-2-face ((t (:foreground ,custom-comment))))
   `(rst-level-3-face ((t (:foreground ,custom-constant))))
   `(rst-level-4-face ((t (:foreground ,custom-comment))))
   `(rst-level-5-face ((t (:foreground ,custom-function))))
   `(rst-level-6-face ((t (:foreground ,custom-comment))))
;;;;; sh-mode
   `(sh-heredoc     ((t (:foreground ,custom-keyword :bold t))))
   `(sh-quoted-exec ((t (:foreground ,custom-string))))
;;;;; show-paren
   `(show-paren-mismatch ((t (:foreground ,custom-comment :background ,custom-white :weight bold))))
   `(show-paren-match ((t (:foreground ,custom-white :background ,custom-keyword :weight bold))))
;;;;; smart-mode-line
   ;; use (setq sml/theme nil) to enable GitHub for sml
   `(sml/global ((,class (:foreground ,custom-comment :weight bold))))
   `(sml/modes ((,class (:foreground ,custom-keyword :weight bold))))
   `(sml/minor-modes ((,class (:foreground ,custom-comment :weight bold))))
   `(sml/filename ((,class (:foreground ,custom-keyword :weight bold))))
   `(sml/line-number ((,class (:foreground ,custom-comment :weight bold))))
   `(sml/col-number ((,class (:foreground ,custom-keyword :weight bold))))
   `(sml/position-percentage ((,class (:foreground ,custom-constant :weight bold))))
   `(sml/prefix ((,class (:foreground ,custom-comment))))
   `(sml/git ((,class (:foreground ,custom-html-tag))))
   `(sml/process ((,class (:weight bold))))
   `(sml/sudo ((,class  (:foreground ,custom-comment :weight bold))))
   `(sml/read-only ((,class (:foreground ,custom-comment))))
   `(sml/outside-modified ((,class (:foreground ,custom-comment))))
   `(sml/modified ((,class (:foreground ,custom-string))))
   `(sml/vc-edited ((,class (:foreground ,custom-comment))))
   `(sml/charging ((,class (:foreground ,custom-constant))))
   `(sml/discharging ((,class (:foreground ,custom-comment))))
;;;;; smartparens
   `(sp-show-pair-mismatch-face ((t (:foreground ,custom-comment :background ,custom-white :weight bold))))
   `(sp-show-pair-match-face ((t (:background ,custom-white :weight bold))))
;;;;; sml-mode-line
   '(sml-modeline-end-face ((t :inherit default :width condensed)))
;;;;; SLIME
   `(slime-repl-output-face ((t (:foreground ,custom-string))))
   `(slime-repl-inputed-output-face ((t (:foreground ,custom-comment))))
   `(slime-error-face
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-string)))
      (t
       (:underline ,custom-string))))
   `(slime-warning-face
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-comment)))
      (t
       (:underline ,custom-comment))))
   `(slime-style-warning-face
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-keyword)))
      (t
       (:underline ,custom-keyword))))
   `(slime-note-face
     ((((supports :underline (:style wave)))
       (:underline (:style wave :color ,custom-comment)))
      (t
       (:underline ,custom-comment))))
   `(slime-highlight-face ((t (:inherit highlight))))
;;;;; speedbar
   `(speedbar-button-face ((t (:foreground ,custom-comment))))
   `(speedbar-directory-face ((t (:foreground ,custom-function))))
   `(speedbar-file-face ((t (:foreground ,custom-comment))))
   `(speedbar-highlight-face ((t (:foreground ,custom-white :background ,custom-comment))))
   `(speedbar-selected-face ((t (:foreground ,custom-string))))
   `(speedbar-separator-face ((t (:foreground ,custom-white :background ,custom-constant))))
   `(speedbar-tag-face ((t (:foreground ,custom-keyword))))
;;;;; tabbar
   `(tabbar-button ((t (:foreground ,custom-comment
                                    :background ,custom-white))))
   `(tabbar-selected ((t (:foreground ,custom-comment
                                      :background ,custom-white
                                      :box (:line-width -1 :style pressed-button)))))
   `(tabbar-unselected ((t (:foreground ,custom-comment
                                        :background ,custom-white
                                        :box (:line-width -1 :style released-button)))))
;;;;; term
   `(term-color-black ((t (:foreground ,custom-white
                                       :background ,custom-selection))))
   `(term-color-red ((t (:foreground ,custom-comment
                                     :background ,custom-comment))))
   `(term-color-green ((t (:foreground ,custom-comment
                                       :background ,custom-comment))))
   `(term-color-yellow ((t (:foreground ,custom-comment
                                        :background ,custom-keyword))))
   `(term-color-blue ((t (:foreground ,custom-constant
                                      :background ,custom-comment))))
   `(term-color-magenta ((t (:foreground ,custom-comment
                                         :background ,custom-string))))
   `(term-color-cyan ((t (:foreground ,custom-function
                                      :background ,custom-comment))))
   `(term-color-white ((t (:foreground ,custom-comment
                                       :background ,custom-comment))))
   '(term-default-fg-color ((t (:inherit term-color-white))))
   '(term-default-bg-color ((t (:inherit term-color-black))))
;;;;; undo-tree
   `(undo-tree-visualizer-active-branch-face ((t (:foreground ,custom-comment :weight bold))))
   `(undo-tree-visualizer-current-face ((t (:foreground ,custom-comment :weight bold))))
   `(undo-tree-visualizer-default-face ((t (:foreground ,custom-comment))))
   `(undo-tree-visualizer-register-face ((t (:foreground ,custom-keyword))))
   `(undo-tree-visualizer-unmodified-face ((t (:foreground ,custom-function))))
;;;;; volatile-highlights
   `(vhl/default-face ((t (:background ,custom-highlight))))
;;;;; web-mode
   `(web-mode-builtin-face ((t (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face ((t (:inherit ,font-lock-constant-face))))
   `(web-mode-css-at-rule-face ((t (:foreground ,custom-comment ))))
   `(web-mode-css-prop-face ((t (:foreground ,custom-constant))))
   `(web-mode-css-pseudo-class-face ((t (:foreground ,custom-html-tag :weight bold))))
   `(web-mode-css-rule-face ((t (:foreground ,custom-html-tag))))
   `(web-mode-doctype-face ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-folded-face ((t (:underline t))))
   `(web-mode-function-name-face ((t (:foreground ,custom-comment))))
   `(web-mode-html-attr-name-face ((t (:foreground ,custom-function))))
   `(web-mode-html-attr-value-face ((t (:inherit ,font-lock-string-face))))
   `(web-mode-html-tag-face ((t (:foreground ,custom-html-tag))))
   `(web-mode-keyword-face ((t (:inherit ,font-lock-keyword-face))))
   `(web-mode-preprocessor-face ((t (:inherit ,font-lock-preprocessor-face))))
   `(web-mode-string-face ((t (:inherit ,font-lock-string-face))))
   `(web-mode-type-face ((t (:inherit ,font-lock-type-face))))
   `(web-mode-variable-name-face ((t (:inherit ,font-lock-variable-name-face))))
   `(web-mode-server-background-face ((t (:background ,custom-white))))
   `(web-mode-server-comment-face ((t (:inherit web-mode-comment-face))))
   `(web-mode-server-string-face ((t (:inherit web-mode-string-face))))
   `(web-mode-symbol-face ((t (:inherit font-lock-constant-face))))
   `(web-mode-warning-face ((t (:inherit font-lock-warning-face))))
   `(web-mode-whitespaces-face ((t (:background ,custom-string))))
;;;;; whitespace-mode
   `(whitespace-space ((t (:background ,custom-white :foreground ,custom-white))))
   `(whitespace-hspace ((t (:background ,custom-white :foreground ,custom-white))))
   `(whitespace-tab ((t (:background ,custom-comment))))
   `(whitespace-newline ((t (:foreground ,custom-white))))
   `(whitespace-trailing ((t (:background ,custom-string))))
   `(whitespace-line ((t (:background ,custom-white :foreground ,custom-comment))))
   `(whitespace-space-before-tab ((t (:background ,custom-comment :foreground ,custom-comment))))
   `(whitespace-indentation ((t (:background ,custom-keyword :foreground ,custom-string))))
   `(whitespace-empty ((t (:background ,custom-keyword))))
   `(whitespace-space-after-tab ((t (:background ,custom-keyword :foreground ,custom-string))))
;;;;; wanderlust
   `(wl-highlight-folder-few-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-folder-many-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-folder-path-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-folder-unread-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-folder-zero-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-folder-unknown-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-citation-header ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-cited-text-1 ((t (:foreground ,custom-string))))
   `(wl-highlight-message-cited-text-2 ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-cited-text-3 ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-cited-text-4 ((t (:foreground ,custom-keyword))))
   `(wl-highlight-message-header-contents-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-headers-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-important-header-contents ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-header-contents ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-important-header-contents2 ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-signature ((t (:foreground ,custom-comment))))
   `(wl-highlight-message-unimportant-header-contents ((t (:foreground ,custom-comment))))
   `(wl-highlight-summary-answered-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-summary-disposed-face ((t (:foreground ,custom-comment
                                                         :slant italic))))
   `(wl-highlight-summary-new-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-summary-normal-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-summary-thread-top-face ((t (:foreground ,custom-keyword))))
   `(wl-highlight-thread-indent-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-summary-refiled-face ((t (:foreground ,custom-comment))))
   `(wl-highlight-summary-displaying-face ((t (:underline t :weight bold))))
;;;;; which-func-mode
   `(which-func ((t (:foreground ,custom-constant))))
;;;;; xcscope
   `(cscope-file-face ((t (:foreground ,custom-keyword :weight bold))))
   `(cscope-function-face ((t (:foreground ,custom-function :weight bold))))
   `(cscope-line-number-face ((t (:foreground ,custom-string :weight bold))))
   `(cscope-mouse-face ((t (:foreground ,custom-white :background ,custom-keyword))))
   `(cscope-separator-face ((t (:foreground ,custom-string :weight bold
                                            :underline t :overline t))))
;;;;; yascroll
   `(yascroll:thumb-text-area ((t (:background ,custom-selection))))
   `(yascroll:thumb-fringe ((t (:background ,custom-selection :foreground ,custom-selection))))

;;;;; elscreen
  `(elscreen-tab-background-face ((t (:background ,custom-keyword))))
  `(elscreen-tab-control-face ((t (:foreground ,custom-white :background ,custom-keyword))))
  `(elscreen-tab-current-screen-face ((t (:foreground ,custom-text :background ,custom-selection))))
  `(elscreen-tab-other-screen-face ((t (:foreground ,custom-text :background ,custom-highlight))))
  ))

;;; Theme Variables
(custom-with-color-variables
  (custom-theme-set-variables
   'custom
;;;;; ansi-color
   `(ansi-color-names-vector [,custom-white ,custom-string ,custom-comment ,custom-keyword
                                          ,custom-comment ,custom-comment ,custom-function ,custom-comment])
;;;;; fill-column-indicator
   `(fci-rule-color ,custom-comment)
;;;;; nrepl-client
   `(nrepl-message-colors
     '(,custom-string ,custom-comment ,custom-keyword ,custom-comment ,custom-constant
                    ,custom-function ,custom-keyword ,custom-comment))
;;;;; pdf-tools
   `(pdf-view-midnight-colors '(,custom-comment . ,custom-highlight))
;;;;; vc-annotate
   `(vc-annotate-color-map
     '(( 20. . ,custom-comment)
       ( 40. . ,custom-string)
       ( 60. . ,custom-comment)
       ( 80. . ,custom-comment)
       (100. . ,custom-comment)
       (120. . ,custom-keyword)
       (140. . ,custom-comment)
       (160. . ,custom-comment)
       (180. . ,custom-comment)
       (200. . ,custom-comment)
       (220. . ,custom-html-tag)
       (240. . ,custom-constant)
       (260. . ,custom-function)
       (280. . ,custom-comment)
       (300. . ,custom-constant)
       (320. . ,custom-comment)
       (340. . ,custom-keyword)
       (360. . ,custom-comment)))
   `(vc-annotate-very-old-color ,custom-comment)
   `(vc-annotate-background ,custom-selection)
   ))

;;; Footer

;;;###autoload
(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

(provide-theme 'custom)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:
;;; custom-theme.el ends here
